// src/components/layout/Header.svelte
<script lang="ts">
  import siteConfig from "@/config/site-config";
  import { getLinkTarget } from "@/lib/utils/link";
  import Icon from "@iconify/svelte";
  import { onMount } from "svelte";
  import ThemeToggle from "../ThemeToggle.svelte";
  import Logo from "@/assets/Logo.svelte";

  const navLinks = siteConfig.header.navLinks || [];

  $: socialLinks = siteConfig.socialLinks.filter((link) => {
    if (link.header && typeof link.header === "boolean") {
      return link;
    }
    if (link.header && typeof link.header === "string") {
      // @ts-ignore
      link.icon = link.header.includes("i-") ? link.header : link.icon;
      return link;
    }
    return false;
  });

  // biome-ignore lint/style/useConst: <explanation>
  let scrollY = 0;
  let oldScrollY = 0;
  let isHeaderHidden = false;

  $: {
    if (scrollY < 150) {
      isHeaderHidden = false;
    } else if (scrollY > oldScrollY && scrollY - oldScrollY > 50) {
      isHeaderHidden = true;
      oldScrollY = scrollY;
    } else if (scrollY < oldScrollY && oldScrollY - scrollY > 50) {
      isHeaderHidden = false;
      oldScrollY = scrollY;
    }
  }

  onMount(() => {
    const navMask = document.querySelector(".nav-drawer-mask") as HTMLElement;
    navMask?.addEventListener("touchmove", (event) => {
      event.preventDefault();
    });
  });
</script>

<svelte:window bind:scrollY />

<header
  id="header"
  class="!fixed bg-transparent z-899 w-screen py-7 px-6 flex justify-between items-center"
  class:header-bg-blur={scrollY > 20}
  class:header-hide={isHeaderHidden}
>
  <div class="flex items-center md:justify-between h-full md:w-full md:pr-6">
    <a aria-label="Header Logo Image" href="/" class="mr-6 md:hidden">
      <Logo />
    </a>
    <nav
      class="w-full sm:flex justify-end hidden flex-wrap gap-x-6 position-initial flex-row"
    >
      {#each navLinks as link (link.text)}
        <a
          aria-label={link.text}
          href={link.href}
          target={getLinkTarget(link.href)}
          class="nav-link"
        >
          {link.text}
        </a>
      {/each}
    </nav>
  </div>

  <div class="flex items-center justify-end w-full gap-x-4 md:w-auto">
    <nav class="flex gap-x-4 items-center justify-end md:hidden">
      {#each navLinks as link (link.text)}
        <a
          aria-label={link.text}
          href={link.href}
          target={getLinkTarget(link.href)}
          class="nav-link"
        >
          <Icon icon={link.icon} class="text-xl" />
        </a>
      {/each}
    </nav>

    <div class="flex gap-x-4">
      {#each socialLinks as link (link.text)}
        <a
          aria-label={link.text}
          class="nav-link"
          href={link.href}
          target={getLinkTarget(link.href)}
        >
          <Icon icon={link.icon} class="text-xl" />
        </a>
      {/each}
      <a aria-label="RSS" href="/rss.xml" class=" nav-link" target="_blank">
        <Icon icon="ri:rss-line" class="text-xl" />
      </a>
      <ThemeToggle />
    </div>
  </div>
</header>

<style>
  .header-hide {
    transform: translateY(-100%);
    transition: transform 0.4s ease;
  }

  .header-bg-blur {
    backdrop-filter: blur(10px);
    transition:
      background-color 0.3s ease,
      backdrop-filter 0.3s ease;
  }
</style>

// src/components/Header.vue
<script lang="ts" setup>
import { useWindowScroll } from '@vueuse/core';
import { computed, onMounted, ref, unref } from 'vue';
import ThemeToggle from './ThemeToggle.vue';
import siteConfig from '@/site-config';
import { getLinkTarget } from '@/utils/link';

const navLinks = siteConfig.header.navLinks || [];

const socialLinks = computed(() => {
  return siteConfig.socialLinks.filter((link: Record<string, any>) => {
    if (link.header && typeof link.header === 'boolean') {
      return link;
    } else if (link.header && typeof link.header === 'string') {
      link.icon = link.header.includes('i-') ? link.header : link.icon;
      return link;
    } else {
      return false;
    }
  });
});

const { y: scroll } = useWindowScroll();

const oldScroll = ref(unref(scroll));

onMounted(() => {
  const navMask = document.querySelector('.nav-drawer-mask') as HTMLElement;

  navMask?.addEventListener('touchmove', (event) => {
    event.preventDefault();
  });

  const headerEl = document.querySelector('#header') as HTMLElement;
  if (!headerEl) return;

  if (document.documentElement.scrollTop > 100)
    headerEl.classList.add('header-bg-blur');

  window.addEventListener('scroll', () => {
    if (scroll.value < 150) {
      headerEl.classList.remove('header-hide');
      return;
    }

    if (scroll.value - oldScroll.value > 150) {
      headerEl.classList.add('header-hide');
      oldScroll.value = scroll.value;
    }

    if (oldScroll.value - scroll.value > 150) {
      headerEl.classList.remove('header-hide');
      oldScroll.value = scroll.value;
    }
  });
});

function toggleNavDrawer(): void {
  const drawer = document.querySelector('.nav-drawer') as HTMLElement;
  const mask = document.querySelector('.nav-drawer-mask') as HTMLElement;
  if (!drawer || !mask) return;
  if (drawer.style.transform === `translateX(0%)`) {
    drawer.style.transform = `translateX(-100%)`;
    mask.style.display = `none`;
  } else {
    drawer.style.transform = `translateX(0%)`;
    mask.style.display = `block`;
  }
}
</script>

<template>
  <header
    id="header"
    :class="{ 'header-bg-blur': scroll > 20 }"
    class="!fixed bg-transparent z-899 w-screen h-20 px-6 flex justify-between items-center relative"
  >
    <div class="flex items-center h-full">
      <a aria-label="Header Logo Image" href="/" mr-6>
        <img
          :alt="siteConfig.header.logo.alt"
          :src="siteConfig.header.logo.src"
          height="32"
          width="32"
        />
      </a>
      <nav class="sm:flex hidden flex-wrap gap-x-6 position-initial flex-row">
        <a
          v-for="link in navLinks"
          :key="link.text"
          :aria-label="`${link.text}`"
          :href="link.href"
          :target="getLinkTarget(link.href)"
          nav-link
        >
          {{ link.text }}
        </a>
      </nav>
      <div flex h-full items-center sm:hidden @click="toggleNavDrawer()">
        <menu i-ri-menu-2-fill />
      </div>
    </div>
    <div class="flex gap-x-6">
      <a
        v-for="link in socialLinks"
        :key="link.text"
        :aria-label="`${link.text}`"
        :class="link.icon"
        :href="link.href"
        :target="getLinkTarget(link.href)"
        nav-link
      />

      <a
        aria-label="RSS"
        href="/rss.xml"
        i-ri-rss-line
        nav-link
        target="_blank"
      />
      <ThemeToggle />
    </div>
  </header>
  <nav class="nav-drawer sm:hidden">
    <i i-ri-menu-2-fill />
    <a
      v-for="link in navLinks"
      :key="link.text"
      :aria-label="`${link.text}`"
      :href="link.href"
      :target="getLinkTarget(link.href)"
      nav-link
      @click="toggleNavDrawer()"
    >
      {{ link.text }}
    </a>
  </nav>
  <div class="nav-drawer-mask" @click="toggleNavDrawer()" />
</template>

<style scoped>
.header-hide {
  transform: translateY(-100%);
  transition: transform 0.4s ease;
}

.header-bg-blur {
  --at-apply: backdrop-blur-sm;
}

.nav-drawer {
  transform: translateX(-100%);
  --at-apply: box-border fixed h-screen z-999 left-0 top-0 min-w-32vw max-w-50vw
    bg-main p-6 text-lg flex flex-col gap-5 transition-all;
}

.nav-drawer-mask {
  display: none;
  --at-apply: transition-all;
  content: '';
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.5);
  z-index: 998;
}
</style>
