// src/components/ThemeToggle.vue
<script lang="ts" setup>
import { useDark, useToggle } from '@vueuse/core';
import { onMounted, watchEffect } from 'vue';

const isDark = useDark();

const toggleDark = useToggle(isDark);

watchEffect(() => {
  if (isDark.value) setDarkMode(document);
});

function setDarkMode(document: Document) {
  if (isDark.value) document.documentElement.classList.add('dark');
}
onMounted(() => {
  document.addEventListener('astro:before-swap', (event) => {
    setDarkMode(event.newDocument);
  });
});

function toggleTheme(event: MouseEvent) {
  const x = event.clientX;
  const y = event.clientY;
  const endRadius = Math.hypot(
    Math.max(x, innerWidth - x),
    Math.max(y, innerHeight - y),
  );

  if (!document.startViewTransition) {
    toggleDark();
    return;
  }

  const transition = document.startViewTransition(async () => {
    toggleDark();
  });

  transition.ready.then(() => {
    const clipPath = [
      `circle(0px at ${x}px ${y}px)`,
      `circle(${endRadius}px at ${x}px ${y}px)`,
    ];
    document.documentElement.animate(
      {
        clipPath: isDark.value ? [...clipPath].reverse() : clipPath,
      },
      {
        duration: 1000,
        easing: 'ease-out',
        pseudoElement: isDark.value
          ? '::view-transition-old(root)'
          : '::view-transition-new(root)',
      },
    );
  });
}
</script>

<template>
  <button
    :aria-label="isDark ? 'Dark Theme' : 'Light Theme'"
    nav-link
    dark:i-ri-moon-line
    i-ri-sun-line
    @click="toggleTheme"
  />
</template>

// src/components/ThemeToggle.svelte
<script lang="ts">
  import { theme } from "@/lib/stores/theme";
  import Icon from "@iconify/svelte";
  import { onMount } from "svelte";

  function setDarkMode(doc: Document) {
    if ($theme === "dark") {
      doc.documentElement.classList.add("dark");
    } else {
      doc.documentElement.classList.remove("dark");
    }
  }

  onMount(() => {
    document.addEventListener("astro:before-swap", (event) => {
      setDarkMode(event.newDocument);
    });
  });

  function handleToggle(event: MouseEvent) {
    const x = event.clientX;
    const y = event.clientY;
    const endRadius = Math.hypot(
      Math.max(x, innerWidth - x),
      Math.max(y, innerHeight - y)
    );

    if (!document.startViewTransition) {
      theme.toggle();
      return;
    }

    const transition = document.startViewTransition(async () => {
      theme.toggle();
    });

    transition.ready.then(() => {
      const clipPath = [
        `circle(0px at ${x}px ${y}px)`,
        `circle(${endRadius}px at ${x}px ${y}px)`,
      ];

      document.documentElement.animate(
        {
          clipPath: $theme === "light" ? clipPath : [...clipPath].reverse(),
        },
        {
          duration: 400,
          easing: "ease-out",
          pseudoElement:
            $theme === "light"
              ? "::view-transition-new(root)"
              : "::view-transition-old(root)",
        }
      );
    });
  }
</script>

<button
  aria-label={$theme === "dark" ? "Dark Theme" : "Light Theme"}
  class="nav-link"
  on:click={handleToggle}
>
  <Icon
    icon={$theme === "dark" ? "ri:sun-line" : "ri:moon-line"}
    class="text-xl"
  />
</button>
